#!/bin/bash

## Go to WD
cd ~/code/

## Create new directory
mkdir new

## move there
cd new/

## Remove old code if it's there
rm -rf mu-internship/

## Clone into repository
git clone -b parallel https://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@github.com/SirPurrcival/mu-internship.git

## transfer ownership
chown -R meowlin mu-internship/

## Go to repository
cd mu-internship/simulation

## switch user
su meowlin

## Execute simulation
python3 run.py
