#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/opt/nrn"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/opt/nrn/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/meowlin/projects/mu_internship/simulation/mod/x86_64/.libs/libnrnmech.so" "$@"
