#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/meowlin/.local/bin"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/meowlin/.local/bin/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/meowlin/projects/LFP_kernel_files/LFPykernels-main/examples/mod/x86_64/.libs/libnrnmech.so" "$@"
